/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElLoading: typeof import('element-plus')['ElLoading']
  const ElMessage: typeof import('element-plus')['ElMessage']
  const ElMessageBox: typeof import('element-plus')['ElMessageBox']
  const useAuth: typeof import('../hooks/use-auth')['useAuth']
  const useBaseForm: typeof import('../hooks/use-base-form')['useBaseForm']
  const useEcharts: typeof import('../hooks/use-echarts')['useEcharts']
  const useFormDialog: typeof import('../hooks/use-form-dialog')['useFormDialog']
  const useI18n: typeof import('../hooks/use-i18n')['useI18n']
  const useLayoutSettings: typeof import('../store/hooks/use-layout-settings')['useLayoutSettings']
  const useLoadView: typeof import('../hooks/use-load-view')['useLoadView']
  const useNotificationState: typeof import('@/components/systems/notifications/use-notification-state')['useNotificationState']
  const usePermissionStore: typeof import('@/store/modules/permission')['usePermissionStore']
  const useSettingState: typeof import('@/components/systems/settings/use-setting-state')['useSettingState']
  const useSettingsStore: typeof import('@/store/modules/settings')['useSettingsStore']
  const useShareSettings: typeof import('../store/hooks/use-share-settings')['useShareSettings']
  const useTheme: typeof import('../hooks/use-theme')['useTheme']
  const useThemeSettings: typeof import('../store/hooks/use-theme-settings')['useThemeSettings']
  const useUserStore: typeof import('@/store/modules/user')['useUserStore']
}
