/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ElAlert: (typeof import('element-plus/es'))['ElAlert'];
  const ElAside: (typeof import('element-plus/es'))['ElAside'];
  const ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
  const ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
  const ElButton: (typeof import('element-plus/es'))['ElButton'];
  const ElCard: (typeof import('element-plus/es'))['ElCard'];
  const ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
  const ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
  const ElCol: (typeof import('element-plus/es'))['ElCol'];
  const ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
  const ElContainer: (typeof import('element-plus/es'))['ElContainer'];
  const ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker'];
  const ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
  const ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
  const ElDialog: (typeof import('element-plus/es'))['ElDialog'];
  const ElDivider: (typeof import('element-plus/es'))['ElDivider'];
  const ElDrawer: (typeof import('element-plus/es'))['ElDrawer'];
  const ElForm: (typeof import('element-plus/es'))['ElForm'];
  const ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
  const ElImage: (typeof import('element-plus/es'))['ElImage'];
  const ElInput: (typeof import('element-plus/es'))['ElInput'];
  const ElLink: (typeof import('element-plus/es'))['ElLink'];
  const ElMenu: (typeof import('element-plus/es'))['ElMenu'];
  const ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
  const ElOption: (typeof import('element-plus/es'))['ElOption'];
  const ElPopover: (typeof import('element-plus/es'))['ElPopover'];
  const ElProgress: (typeof import('element-plus/es'))['ElProgress'];
  const ElRadio: (typeof import('element-plus/es'))['ElRadio'];
  const ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
  const ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
  const ElSegmented: (typeof import('element-plus/es'))['ElSegmented'];
  const ElSelect: (typeof import('element-plus/es'))['ElSelect'];
  const ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
  const ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
  const ElTable: (typeof import('element-plus/es'))['ElTable'];
  const ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
  const ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
}
